SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components;

public class CartSummaryViewComponent(Cart cart) : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View(cart);
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Product

<div class="card">
    <h3>
        <strong>@Model.Name</strong>
        <span class="float-start badge bg-primary">@Model.Price.ToString("c")</span>
    </h3>
    <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="lead">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm float-start">Add To Cart</button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/css/*.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script asp-src-include="lib/jquery/jquery.js"></script>
    <script asp-src-include="lib/jquery-validate/jquery.validate.js"></script>
    <script asp-src-include="lib/jquery-validate/jquery.validate.unobtrusive.js"></script>
</head>
<body class="card">
    <div class="card-header">
        <h4>
            @ViewBag.Title
            <a class="btn btn-sm btn-primary float-start" asp-action="Logout" asp-controller="Account">Log Out</a>
        </h4>
    </div>
    <div class="panel-body">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>    
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/css/*.css" />
    <link rel="stylesheet" asp-href-include="lib/fontawesome/css/*.css" />
    <title>Sports Store</title>
</head>
<body>
    <div class="navbar navbar-dark bg-dark" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        <div class="float-start">@await Component.InvokeAsync("CartSummary")</div>
    </div>
    <div class="row">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>